on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ https://sonar.asian-technology.com/ }}
        login: ${{ 3bb754de3237f363802b97123bed1a219c7b2e41 }}
