-name: Setup sonarqube
uses: warchant/setup-sonar-scanner@v3
 
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: sonar-scanner
       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
       -Dsonar.organization=1corp
       -Dsonar.host.url=https://sonarcloud.io/
       -Dsonar.projectKey=sonar-scanner-action
